### ISSUE TITLE
1.08

### ISSUE THREAD

**Issue by crlfx68** [novvvels/WuxiaNovvvels#1]
In all nice app,after update i try if fixed errors,,with download on description page+just too low amount of novels almost all has no more than 50 chaps within ehh)think dont needed this button 50chaps download.
There change to: add window where you choose from which to which chap download (112-235) or download all

**Comment by crlfx68** [comment]
Thks for fix with download on description page)mm now found another when downloaded novel and then click download list always error.
Add pls function for update new chaps for downloaded novels(click one button and all updates)now with this really terrible

**Comment by novvvels** [comment]
> In all nice app,after update i try if fixed errors,,with download on description page+just too low amount of novels almost all has no more than 50 chaps within ehh)think dont needed this button 50chaps download.
> There change to: add window where you choose from which to which chap download (112-235) or download all

In fact, most of the Chinese Novels has more than 50 chapters. So this options is used in that case: 50 ch is faster than download all ch. so user can just download 50 ch for reading in one day.

**Comment by novvvels** [comment]
> Thks for fix with download on description page)mm now found another when downloaded novel and then click download list always error.
> Add pls function for update new chaps for downloaded novels(click one button and all updates)now with this really terrible
1. Thanks for report this issue. we will check it.
2. Do you mean that it automatically downloads all new chapters of the books in bookshelf?

**Comment by crlfx68** [comment]
2)yes now a little confusing how add new released chaps to already downloaded novels on bookshelf

\\\you later add new methods of registration aside google?

**Comment by novvvels** [comment]
> little confusing how add new released chaps to already downloaded novels o

Currently, new released ch will not be download automatically, you can only download it manually.We will consider this issue.
We will add new method of registration and which one do you want to add?

**Comment by crlfx68** [comment]
internal(your database) better and twitter
Want ask: why when you type in search,sometimes appear 2 similiar novels(names and chaps)but different covers @_@

**Comment by dioaizazach** [comment]
Why i cant download this apps again .....after i update the version....i cant run the apps that is why i uninstalled the apps and try to install using the apk u tag...but i cant install the apps...pls help me..

**Comment by crlfx68** [comment]
> 
> 
> Why i cant download this apps again .....after i update the version....i cant run the apps that is why i uninstalled the apps and try to install using the apk u tag...but i cant install the apps...pls help me..

Think app was deinstalled from play google,so if you deleted from phone,you dont recover this old app,search something else similiar

**Comment by dioaizazach** [comment]
Thanks... I already recovered it...

**Comment by novvvels** [comment]
> Why i cant download this apps again .....after i update the version....i cant run the apps that is why i uninstalled the apps and try to install using the apk u tag...but i cant install the apps...pls help me..

we will check this issue, we need some information about your phone brand, android version and so on.

**Comment by Anyikizit** [comment]
Since 2days now i have not been able to update/download new chapters its keeps saying last page when it remind more than 500 pages 🤔.... I have tried everything yet its not working. I keep getting a reply (connection refuses)

**Comment by crlfx68** [comment]
read above)think you already dont load anything new;D
