### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by AvengeMeBolo** [novvvels/WuxiaNovvvels#12]
Books are not opening anymore for me. New books from bookstore also wont load. It just shows loading screen. 
Please look into this.
Thank you.

**Comment by kalistrea** [comment]
i have also got thos problem so do my sister.

**Comment by kalistrea** [comment]
all their weblinks are down and email?  i hope this aint the end of the app.  please do not die app you the only one holding me together.....

**Comment by novvvels** [comment]
Hello all,
The service is lost due to the fee of server is ran out.
We have recovered the service now.
Please try it again
