### ISSUE TITLE
Connection/Server Problem (or whatever)

### ISSUE THREAD

**Issue by Permissiv3** [novvvels/WuxiaNovvvels#4]
I already submitted the error through gmail but I decided to write it again here. So the issue is that I cannot view, read, download, search, and even login with my account because of "Connection Problems" (my wifi is good btw) the app "refuses" to load things for me. I hope you can fix this as I love this app. :)

**Comment by Permissiv3** [comment]
Fixed now :D keep up the good work! Should I close this? Or should I keep it like this just in case it happens again?

**Comment by Permissiv3** [comment]
Wait, another issue just popped up! :/ Which is missing chapters/novels

**Comment by novvvels** [comment]
The server meet some errors. we have already fix it and also fixed the chapters missing issue.
