### ISSUE TITLE
Missing chapters or novels (like a lot are missing)

### ISSUE THREAD

**Issue by Permissiv3** [novvvels/WuxiaNovvvels#6]
After reinstalling the app I found out that some of my favorite new novels or chapters from certain novels are missing! Please fix this issue :/

**Comment by Permissiv3** [comment]
I would like the creator of this app to fix this as soon as possible as this is one of my favorite apps that are out there.

**Comment by Cassie724** [comment]
I have same issues too

**Comment by Permissiv3** [comment]
I was only stockpiling some chapters and this suddenly happened and I could not read them anymore :( ;-;

**Comment by novvvels** [comment]
This issue is caused by server data error and it's fixed.
please reload the book to get latest data.

**Comment by Cassie724** [comment]
I have the same issue, about 5 chapters are missing from one of my favorite book titled 
 "it's not easy to be a man after traveling to the future by Madam R" can you guys please fix it
